import type { Metadata } from "next";
import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import NavBar from './NavBar/page';
import Splash from './Splash/page';
// Votre code Next.js continue ici

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Garista</title>
      </head>
      
      <body className={inter.className}>
      <Splash/>
      <NavBar/>
        {children}
        </body>
    </html>
  );
}
